Add styling to components
Dinma-Faith/BookStore pull request #5
Opened 2022-06-11 19:54 UTC by Dinma-Faith

**In this final milestone I did the following**
 
 * Style Project UI following  [Zipline Design](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/sneak_peek.md)
 * Apply React best practices and language style guides in code.

2022-06-11 22:57 UTC, medaminedev66 requested changes
Hi @Dinma-Faith 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Your design looks great 👏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-11 22:57 UTC, medaminedev66 commented on src/components/book.js
> +        <button type="button" className="update-btn">UPDATE PROGRESS</button>
- [ ] As requested by the previous reviewer:
- Kindly use the same font used in the template.
- Kindly add a border-radius around the 'Update progress' button.

2022-06-11 22:57 UTC, medaminedev66 commented on src/components/book.js
> +          <div style={{ width: 100, height: 100 }}>
- [ ] As requested by the previous reviewer, Kindly avoid inline styling. It is one of CSS bad practices. When you add inline styles, it makes it difficult revising the design of your site and makes your code harder to manage.
I would recommend moving the style out of the `div`. Try to define a constant `style` in the `Book` component and give it to the style attribute in the div.

2022-06-11 22:57 UTC, medaminedev66 commented on src/components/form.js
> +        <button className="btn" type="submit">Add Book</button>
- [ ] As requested by the previous reviewer:
- Kindly ensure the border around the input field is the same color as the one in the Zeplin design
- Kindly align the input fields and the button as it is aligned in the template.
- Kindly add a border-radius around the add button.
- Kindly use the font family provided in the template.

2022-06-11 22:57 UTC, medaminedev66 commented on src/components/book.js
> +      </ul>
- [ ] As requested by the previous reviewer,  for all text kindly use the font family provided in the template.

2022-06-13 09:23 UTC, keneogu approved these changes
> ## Hi @Dinma-Faith,
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
> 
> ## Congratulations!     
> Cheers and Happy coding!clapclapclap
> 
> ![image](https://camo.githubusercontent.com/2366be437d35bce33dd123620530e9131a8ac147fe960e76a36614dc703e8e22/68747470733a2f2f692e70696e696d672e636f6d2f6f726967696e616c732f37372f30652f62302f37373065623035373434393538326334343637326232643264316363333962362e676966) [ ](https://camo.githubusercontent.com/2366be437d35bce33dd123620530e9131a8ac147fe960e76a36614dc703e8e22/68747470733a2f2f692e70696e696d672e636f6d2f6f726967696e616c732f37372f30652f62302f37373065623035373434393538326334343637326232643264316363333962362e676966) ![image](https://camo.githubusercontent.com/2366be437d35bce33dd123620530e9131a8ac147fe960e76a36614dc703e8e22/68747470733a2f2f692e70696e696d672e636f6d2f6f726967696e616c732f37372f30652f62302f37373065623035373434393538326334343637326232643264316363333962362e676966) [ ](https://camo.githubusercontent.com/2366be437d35bce33dd123620530e9131a8ac147fe960e76a36614dc703e8e22/68747470733a2f2f692e70696e696d672e636f6d2f6f726967696e616c732f37372f30652f62302f37373065623035373434393538326334343637326232643264316363333962362e676966)
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-13 12:27 UTC, merged